inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
