inherit_from:
  - .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
